library(RCurl)
library(plotrix) # Gives us the scale we need
library(jsonlite)

#Finding the bridge
# TODO: https://huetips.com/help/how-to-find-my-bridge-ip-address/


#' Gets IP address from Hue Bridge
#'
#' @return IP
#' @examples
#' getIP()
getIP <- function()
{
  url <- paste0("https://www.meethue.com/api/nupnp")
  res <- httpGET(url)
  resJson <- fromJSON(res)
  res <- resJson[["internalipaddress"]]
  res
}


#' Creates a list of available lights
#'
#' @param ip IP address generated by getIP()
#' @param userName A username key
#' @return Returns a list of lights to be changed


getLights <- function(ip, userName)
{
  ip <- getIP()
  url <- paste0("http://",ip,"/api/",userName,"/lights/")
  #content <- paste0('{"on":',state,'}')
  res <- httpGET(url)
  res
}


#' Turn a single light on and off
#'
#' @param ip IP address generated by getIP()
#' @param userName A username key
#' @param light Light number created
#' @return Changes the state of On / Off of a light
#' @examples
#' changeLightOnOff("0.0.0.0", "XXXXXX", 1, "true")
#'
turnLightOnOff <- function(ip, userName, light, state)
{
  url <- paste0("http://",ip,"/api/",userName,"/lights/",light,"/state")
  content <- paste0('{"on":',state,'}')
  res <- httpPUT(url,content)
  res
}


#' Change Brightness of a light
#'
#' @param ip IP address generated by getIP()
#' @param userName A username key
#' @param light An available light number
#' @param  brightness Brightness between (1 - 254)
#' @return Changes the brightness of the light
#' @examples
#' changeBrightness("0.0.0.0","Xo12x",1,255)

changeBrightness <- function(ip, userName, light,brightness)
{
  ip <- getIP()
  url <- paste0("http://",ip,"/api/",userName,"/lights/",light,"/state")
  content <- paste0('{"bri":',as.string(brightness),'}')
  res <- httpPUT(url,content)
  res
}



#' Change hue of a light
#'
#' @param ip IP address generated by getIP()
#' @param userName A username key
#' @param light An available light number
#' @param  hue Hue between (0 - 65535)
#' @return Changes the hue of the light
#' @examples
#' changeHue(ip,userName,light,"254")
changeHue <- function(ip, userName, light,hue)
{
  url <- paste0("http://",ip,"/api/",userName,"/lights/",light,"/state")
  content <- paste0('{"hue":',hue,'}')
  res <- httpPUT(url,content)
  res
}

#' Change light effect
#'
#' @param ip IP address generated by getIP()
#' @param userName A username key
#' @param light An available light number
#' @param effect
#'
#' @return The sum of \code{x} and \code{y}
#' @examples
#' changeEffect("0.0.0.0","XXXX",1,"Carsol")


changeEffect <- function(ip, userName, light,effect)
{
  url <- paste0("http://",ip,"/api/",userName,"/lights/",light,"/state")
  content <- paste0('{"effect":"',effect,'"}')
  res <- httpPUT(url,content)
  res
}

#' Make the lights blink as an allerting effect
#'
#' @param ip IP address generated by getIP()
#' @param userName A username key
#' @param light An available light number
#' @return Have the lights alert
#' @examples
#' alertLights("0.0.0.0", "XXXX", 1)

alertLights <- function(ip, userName, light)
{
  url <- paste0("http://",ip,"/api/",userName,"/lights/",light,"/state")
  content <- paste0('{"alert":"select"}')
  res <- httpPUT(url,content)
  res
}
